In [1]:
"""Soru 1 – Liste Metotları
Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
• Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
• En yüksek ve en düşük notu bulun.
• Notları küçükten büyüğe sıralayın.
"""
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

i = 0
max = notlar[0]
min = notlar[0]

while i < len(notlar):
    if notlar[i] > max:
        max = notlar[i]
    if notlar[i] < min:
        min = notlar[i]
    i += 1

print("En yuksek not:", f'{max}')
print("En dusuk not:", f'{min}')
notlar.sort()
print("Notlarin kucukten buyuge siralamasi:", notlar)


En yuksek not: 100
En dusuk not: 76
Notlarin kucukten buyuge siralamasi: [76, 76, 85, 85, 92, 92, 92, 100]


In [2]:
"""Soru 2 – Sayılar
Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.
Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.
Örn: 153 → 1³+5³+3³ = 153"""

def Amstrong(sayi):
    toplam = 0
    temp = sayi
    while temp > 0:
        basamak = temp % 10      
        toplam += basamak ** 3    
        temp //= 10              
    if toplam == sayi:
        print(sayi, "bir Armstrong sayisidir.")
    else:
        print(sayi, "bir Armstrong sayisi degildir.")

sayi = int(input("Armstrong olup olmadigini anlamak icin sayiyi giriniz: "))
Amstrong(sayi)


Armstrong olup olmadigini anlamak icin sayiyi giriniz:  153


153 bir Armstrong sayisidir.


In [3]:
"""Soru 3 – Kümeler
Aşağıdaki iki küme verilmiştir:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
• Ortak dilleri bulun.
• Sadece A’da olan dilleri listeleyin.
• İki kümenin birleşimini alfabetik olarak yazdırın."""

A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

print("Kumelerdeki ortak diller:", A.intersection(B))


print("Sadece A da olan diller:", A.difference(B))

birlesim = sorted(A.union(B))
print("Birleşim (alfabetik):", birlesim)


Kumelerdeki ortak diller: {'Python', 'SQL'}
Sadece A da olan diller: {'R', 'Java'}
Birleşim (alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [4]:
"""Soru 4 – Modüller
• random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
• Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın."""

import random
import statistics


sayilar = []
for i in range(10):
    sayilar.append(random.randint(1, 100))

print("Rastgele sayilar:", sayilar)

toplam = 0
for j in range(10):
    toplam += sayilar[j]

ortalama = toplam / 10
print("Ortalama :", ortalama)

farkkareleri = 0
for k in range(10):
    farkkareleri += (sayilar[k] - ortalama) ** 2

sapma = (farkkareleri / (10 - 1)) ** 0.5
print("Standart sapma :", sapma)

# Ortalama (statistics modülü ile)
print("Ortalama (statistics):", statistics.mean(sayilar))

# Standart sapma (statistics modülü ile)
print("Standart sapma:", statistics.stdev(sayilar))


Rastgele sayilar: [5, 58, 70, 36, 22, 83, 51, 73, 80, 98]
Ortalama : 57.6
Standart sapma : 29.27721905433567
Ortalama (statistics): 57.6
Standart sapma: 29.277219054335667


In [1]:
"""Soru 5 – Fonksiyonlar
kelime_sayacı(metin) adında bir fonksiyon yazın.
Fonksiyon verilen metindeki:
• toplam kelime sayısını
• en uzun kelimeyi
• en sık geçen kelimeyi döndürsün."""

toplam=0
uzun=0
kisa=0

def kelimesayaci(metin):
    kelimeler = metin.split()

    uzun = max(kelimeler, key=len)
    kisa = max(kelimeler, key=kelimeler.count)
    toplam = len(kelimeler)

    return toplam,uzun,kisa


cumle = input("Bir cumle kurunuz: ")

toplam, uzun,kisa  = kelimesayaci(cumle)

print("Toplam kelime sayisi:", toplam)
print("En uzun kelime:", uzun)
print("En cok gecen kelime:", kisa) 

Bir cumle kurunuz:  malatya malatya bulunmaz eşin


Toplam kelime sayisi: 4
En uzun kelime: bulunmaz
En cok gecen kelime: malatya


In [2]:
"""Soru 6 – Gömülü Fonksiyonlar
Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
sayilar = [5, 12, 7, 18, 24, 3, 16]
• Sadece çift sayıları filtreleyin.
• Bu sayıların karelerini bulun.
• Karelerini azalan sırada sıralayın."""


sayilar = [5, 12, 7, 18, 24, 3, 16]

i=0
cift=[]
kare=[]
while(i<len(sayilar)):
    if(sayilar[i]%2==0):
        cift.append(sayilar[i])
    
    kare.append(sayilar[i]**2)
    
    
    i+=1
print(cift)
print(kare)
kare.sort()
print("Sirali liste:", kare)

sayilar = [5, 12, 7, 18, 24, 3, 16]

# 1️⃣ Sadece çift sayıları filtrele
cift = list(filter(lambda x: x % 2 == 0, sayilar))

# 2️⃣ Bu sayıların karelerini bul
kare = list(map(lambda x: x**2, cift))

# 3️⃣ Karelerini azalan sırada sırala
sirali = sorted(kare, reverse=True)

print("Çift sayılar:", cift)
print("Kareleri:", kare)
print("Azalan sırada:", sirali)



[12, 18, 24, 16]
[25, 144, 49, 324, 576, 9, 256]
Sirali liste: [9, 25, 49, 144, 256, 324, 576]
Çift sayılar: [12, 18, 24, 16]
Kareleri: [144, 324, 576, 256]
Azalan sırada: [576, 324, 256, 144]


In [3]:
"""Soru 7 – Lambda İfadeleri
Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
Bunu sorted + lambda ile yapın.
"""

kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sirali = sorted(kelimeler, key=lambda x: len(x))

print(sirali)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [4]:
"""Soru 8 – Metodlar
Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon
yazın.
Örn: "abc12def3" → 12 + 3 = 15"""

def rakamtoplami(metin):
    sayi = ""
    toplam = 0

    for ch in metin:
        if ch.isdigit():          
            sayi += ch            
        else:
            if sayi != "":       
                toplam += int(sayi)
                sayi = ""          
    
    if sayi != "":                 
        toplam += int(sayi)

    return toplam


print("Rakamlarin toplami:", rakamtoplami( input("Bir ifade girin: ")))


Bir ifade girin:  rfjkerk45kdfklvdkllkdlfdg5kdlfkldflkdl12skflkskvşkşdsş3sfşlslşdlşvskslş5dsşvşlv


Rakamlarin toplami: 70


In [7]:
"""Soru 9 – (Ekstra) Numpy 1
10 elemanlı bir numpy dizisi oluşturun.
• Elemanlar 0–50 arasında rastgele sayılar olsun.
• Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun."""

import numpy as np


dizi = np.random.randint(0, 51, size=10)

print("Dizi:", dizi)


ortalama = np.mean(dizi)
print("Ortalama:", ortalama)


std_sapma = np.std(dizi)
print("Standart sapma:", std_sapma)


en_buyuk = np.max(dizi)
print("En büyük değer:", en_buyuk)


Dizi: [10 44 46 45 27 34 13 44 31  9]
Ortalama: 30.3
Standart sapma: 14.241137595009747
En büyük değer: 46


In [8]:
"""Soru 10 – (Ekstra) Numpy 2
5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.
• Her sütunun ortalamasını bulun.
• 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun"""

import numpy as np


matris = np.random.rand(5, 5)
print("Orijinal matris:\n", matris)


sutun_ortalama = np.mean(matris, axis=0)
print("Sütun ortalamaları:", sutun_ortalama)


binary_matris = np.where(matris > 0.5, 1, 0)
print("Binary matris:\n", binary_matris)


Orijinal matris:
 [[0.11389986 0.53344377 0.57731717 0.18288358 0.61985642]
 [0.53854127 0.17815066 0.87017349 0.90343872 0.22368973]
 [0.12671943 0.48280702 0.89291624 0.71004842 0.94197618]
 [0.61141411 0.61030581 0.61986882 0.93102444 0.68692716]
 [0.663775   0.56837656 0.08191183 0.0871021  0.65181088]]
Sütun ortalamaları: [0.41086993 0.47461676 0.60843751 0.56289945 0.62485208]
Binary matris:
 [[0 1 1 0 1]
 [1 0 1 1 0]
 [0 0 1 1 1]
 [1 1 1 1 1]
 [1 1 0 0 1]]
