In [1]:
import numpy as np

In [7]:
arr3d=np.array([[ [1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[1,2,3]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [ 1,  2,  3]]])

In [8]:
arr3d.ndim

3

In [9]:
arr3d.shape

(2, 3, 3)

BİR ARRAY İ RESHAPE(YENİDEN ŞEKİLLENDİRME) ETME


In [10]:
# .reshape() methodu arraylarin şeklini değiştirir 
# toplam eleman sayısını sabit tutmaya yarar

In [13]:
arr3d.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 20, 30],
       [40, 50, 60,  1,  2,  3]])

In [14]:
arr2d=np.arange(30)

In [15]:
arr2d


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
arr2d.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [17]:
arr2d=np.arange(30).reshape(5,6)

In [18]:
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
# bilinmeyen boyut
# .reshape() methodu kullanılırken hesaplamak istediğimiz boyut yerine -1 yazıp otomatik hesaplatabiliriz

In [20]:
arr3d=np.arange(120).reshape(5,2,-1)

In [21]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

In [26]:
 arr3d=np.arange(60).reshape(2,-1,5)

arr3d.dtype

dtype('int64')

In [27]:
arr3d.ndim

3

In [28]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

ARRAYLARİ DÜZLEŞTİRME

In [29]:
# düzleştirme işlemi (FLATTEN) ÇOK BOYUTLU BİR ARRAYİ 1 boyutlu arraya çevirme
# basitçe .reshape(-1) methoduyla yapılır

In [30]:
arr2d=np.arange(40).reshape(8,5)

In [31]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [32]:
arr2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [35]:
arr3d=np.random.randint(1,100,30).reshape(2,-1,3)
arr3d

array([[[28,  9, 62],
        [59, 16, 99],
        [73, 62, 17],
        [16, 79, 83],
        [84, 87, 63]],

       [[10, 49, 46],
        [71, 15,  2],
        [70, 17, 34],
        [15, 25,  6],
        [50, 77, 80]]], dtype=int32)

In [36]:
arr3d.reshape(-1)

array([28,  9, 62, 59, 16, 99, 73, 62, 17, 16, 79, 83, 84, 87, 63, 10, 49,
       46, 71, 15,  2, 70, 17, 34, 15, 25,  6, 50, 77, 80], dtype=int32)

ÇOK BOYUTLU ARRAYLARDA İTERATİON(YİNELEME)

In [37]:
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
for x in arr1d:
    print(x)

0
1
2
3
4
5
6
7
8
9


In [41]:
arr2d=np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
for x in arr2d:
    print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [43]:
for x in arr2d:
    for y in x:
        print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [44]:
arr3d=np.arange(30).reshape(2,3,-1)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

ÇOK BOYUTLU ARRAYLARDA nditer() KULLANIMI

In [45]:
# for döngüsünde arrrayin boyutu kadar for yazarsak bütün elemanlara ulaşırız
#çok boyutlu arraylarda nditer() fonlsiyonu bunun için geçerlidir
# for döngüsüne çok daha efektif ve hızlı bir şekilde tüm elemanları dönmemimizi sağlar

In [46]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [47]:
np.nditer(arr3d)

In [48]:
for x in np.nditer(arr3d):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [49]:
arr3d=np.arange(120).reshape(-1,4,30)
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
          54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
          72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
         102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118, 119]]])

In [50]:
for x in np.nditer(arr3d):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


ARRAY ELEMANLARI ARASINDA 4 İŞLEM

In [54]:
arr1d=np.array([10,20,30,40])
arr2d=np.array([10,200,3,40])

In [56]:
arr2d

array([ 10, 200,   3,  40])

In [57]:
arr1d

array([10, 20, 30, 40])

In [58]:
arr1d+arr2d

array([ 20, 220,  33,  80])

In [60]:
arr1d.__add__(arr2d)

array([ 20, 220,  33,  80])

BİR ARRAYİN ORT TOP VAR STANDART SAPMASINA NASIL BAKILIR

In [61]:
arr=np.random.randint(0,10,10)

In [62]:
arr

array([5, 8, 1, 2, 1, 2, 4, 1, 6, 8], dtype=int32)

In [63]:
arr.sum()

np.int64(38)

In [64]:
arr.mean()

np.float64(3.8)

In [65]:
arr.var()

np.float64(7.159999999999999)

In [66]:
arr.std()

np.float64(2.6758176320519302)

In [67]:
arr

array([5, 8, 1, 2, 1, 2, 4, 1, 6, 8], dtype=int32)

In [68]:
np.sqrt(arr)

array([2.23606798, 2.82842712, 1.        , 1.41421356, 1.        ,
       1.41421356, 2.        , 1.        , 2.44948974, 2.82842712])

In [69]:
np.sin(arr)

array([-0.95892427,  0.98935825,  0.84147098,  0.90929743,  0.84147098,
        0.90929743, -0.7568025 ,  0.84147098, -0.2794155 ,  0.98935825])

NUMPY ARRAYLARİNİ BİRLEŞTİRME(CONCATANATE)

In [70]:
# Numpy arratlarini birleştirme .concatenate() fonksiyonun içine birleştirilecek arraylar verilir
# np.concatenate([arr1,arr2],axis=1)


In [71]:
arr1=np.array([10,23,45])
arr2=np.array([2,4,56])

In [72]:
arr1

array([10, 23, 45])

In [73]:
arr2

array([ 2,  4, 56])

In [74]:
np.concatenate([arr1,arr2],axis=0)

array([10, 23, 45,  2,  4, 56])

In [82]:
arr2d=np.random.randint(0,30,10)
arr2d

array([17, 29,  4, 11, 11,  3,  4,  9,  2, 14], dtype=int32)

In [89]:
arr2d=arr2d.reshape(2,5,)
arr2d

array([[17, 29,  4, 11, 11],
       [ 3,  4,  9,  2, 14]], dtype=int32)

In [95]:
arr2d1=np.array([[3,4,5],[7,8,9]])
arr2d1

array([[3, 4, 5],
       [7, 8, 9]])

In [100]:
np.concatenate([arr2d,arr2d1],axis=1)   #eksen

array([[17, 29,  4, 11, 11,  3,  4,  5],
       [ 3,  4,  9,  2, 14,  7,  8,  9]])

ARRAYLARİ YIĞINLAMA(STACKLEME) İŞLEMLERİ

In [101]:
# concatenate işleminin hemen hemen aynısııdr tek farkı yeni bir boyut(eksen üzerinde) yığınlamalar yapmasıdır

In [106]:
arr1=np.random.randint(0,30,10)
arr1

array([24, 12, 13,  2, 28, 16,  7, 28, 19, 20], dtype=int32)

In [111]:
arr2=np.random.randint(0,20,10)
arr2

array([14, 19,  0, 14,  4, 19, 19,  7,  5,  7], dtype=int32)

In [112]:
np.concatenate([arr1,arr2],axis=0)

array([24, 12, 13,  2, 28, 16,  7, 28, 19, 20, 14, 19,  0, 14,  4, 19, 19,
        7,  5,  7], dtype=int32)

In [114]:
np.stack([arr1,arr2],axis=0)   # yeni bir eksen koyar  

array([[24, 12, 13,  2, 28, 16,  7, 28, 19, 20],
       [14, 19,  0, 14,  4, 19, 19,  7,  5,  7]], dtype=int32)

In [115]:
#  np.hstack()  satur boyunca yığınlAMA
# np.vstack()   sutün boyunca yığınlama

NUMPY ARRAYLARINDA ARAMA

In [116]:
#  aradığımız değerlerin bulundupu indexleri döndürmek için np.where() fonksiyonu kullanırız
#  np.where() içersine argüman olarak condition(şart) alır

In [121]:
arr=np.random.randint(0,10,8)
arr

array([3, 0, 7, 1, 9, 7, 0, 6], dtype=int32)

In [122]:
np.where(arr==9)


(array([4]),)

In [123]:
np.where(arr==7)

(array([2, 5]),)

In [124]:
np.where(arr%2!=0)

(array([0, 2, 3, 4, 5]),)

NUMPY DA RANDOM KÜTÜPHANESİ

In [125]:
#  random diye ayrı bir kütüphane olmasının yanında numpy kütüphanesinin içinde random adında kütüphane bulunur
# numpy ın iiçindeki randım kütüphanesi normal random kütüphanesinden daha kapsamlıdır

In [126]:
# from numpy import random as rd dersek rd ile çağırırız
import numpy as np

In [129]:
np.random.randn(5)   #  normal dağılımdan 5 tane veri çek


array([-1.91553806,  0.36190028, -1.34870175,  1.17487318,  0.93427448])

In [130]:
np.random.choice(arr)

np.int32(7)

In [132]:
np.random.choice(np.random.randint(0,30,10))

np.int32(2)

In [ ]:
a