In [2]:
#sayılarla daha hızlı matematik işlemler yaparız
#python da array yok liste şeklinde çok boyutlu
#hızlıdır arraylardan 50 kat hızlıdır
#hızlı çalışmasının nedeni c ve c++ ile yazılması python kütühanleri daha hızlı çalışması için c de yazıır
#

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy np

SyntaxError: invalid syntax (1904197115.py, line 1)

In [6]:
import numpy as np

NUMPY ARRAYLARI OLUŞTURMA

In [7]:
#np.array([1,2,3])   #liste ya da tuple benzeri nesneleri arraya çevirebiliriz
#np.arrange() , np.linspace(), np.logspace()  #Built-in hazır fonksiyonları
#rastgele data üreterek

In [8]:
arr0d=np.array(53)
print(arr0d)

53


In [9]:
arr1d=np.array([1,2,3])
print(arr1d)

[1 2 3]


In [10]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[110,200,300]]])
print(arr3d)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [110 200 300]]]


In [12]:
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


In [13]:
print(arr3d[0][0])
print(arr3d[0,0])

[1 2 3]
[1 2 3]


BUİLT İN FONKSİYONLARLA HIZLICA ARRAYLAR OLUŞTURMA


In [14]:
#np.arange(start,stop,step) start dahil stop dahil değil

In [19]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
np.arange(0,10,2) #burada hızlıca arraylar oluşturmak için kullanılır

array([0, 2, 4, 6, 8])

In [25]:
np.linspace(30,50,6)    #burada start stop dahil float şekilde ilerler
   

array([30., 34., 38., 42., 46., 50.])

In [23]:
np.logspace(1,3,10)   # 10 üssü 1 ile 10 üssü 3 arasında logaritmiik artış yapan 10 tane veriden oluşan veri oluştur

array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
         77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
        599.48425032, 1000.        ])

In [26]:
np.linspace(30,50,6, dtype=int) #burada 6 tane veri al 30 ile 50 arasınd arttır

array([30, 34, 38, 42, 46, 50])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [31]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
np.zeros(((2,3,4)))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [37]:
np.ones(((2,3,4)))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [40]:
np.eye(5,dtype=int) #burada 5*5 birim matris

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [41]:
#burada np.random modülünü kullanaral rastgele veriler arraylar

In [43]:
np.random.rand(10) #burada 10 tane 0 ile 1 arasında sayılar dönüştürdü

array([0.66327515, 0.92222946, 0.89565939, 0.43480889, 0.37064955,
       0.01462006, 0.97367319, 0.28931846, 0.22656484, 0.58432172])

In [46]:
np.random.rand(2,5)  #burada tuple olarak verilmiyor

array([[0.07509301, 0.1124786 , 0.95510119, 0.3991362 , 0.43318062],
       [0.23653089, 0.64288037, 0.51162351, 0.69013935, 0.70309308]])

In [47]:
np.random.rand(2,5)*10

array([[3.47885468, 1.1454206 , 7.54182501, 0.83150551, 9.02298429],
       [7.00900021, 5.35948142, 7.90924897, 1.23957658, 1.84123086]])

In [48]:
np.random.randint(10)

8

In [50]:
np.random.randint(15,50,5) #burada 15 ile 50 arasında 5 sayı oluştur

array([43, 36, 19, 15, 30], dtype=int32)

In [52]:
np.random.randint(0,100,(3,6))  #burada start stop size 

array([[77, 23, 59, 79, 86, 23],
       [56, 17, 56, 48, 50, 99],
       [51,  6, 42, 45, 77, 84]], dtype=int32)

In [54]:
np.random.randint(0,50,(4,6))

array([[39, 13, 21,  6, 47, 16],
       [11, 22,  2, 17, 36, 40],
       [39, 29, 18, 37, 42, 11],
       [32,  8,  4, 21, 12, 24]], dtype=int32)

ARRAYİN BOYUT SAYISIMI VE SHAPE İNİ KONTROL ETMEK

In [55]:
arr0d

array(53)

In [56]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [110, 200, 300]]])

In [58]:
#.ndim attribute i ile arrayimizin kaç boyutlu olduğuna bakabiliriz

In [59]:
arr3d.ndim

3

In [61]:
arr2d.shape #burada .shape ile boyutuna bakılabilir

(3, 3)

In [62]:
arr3d.shape

(2, 2, 3)

NUMPY ARRAYLARİNİ İNDEXLEME VE ÖGELERE ERİŞME

In [64]:
arr1d  #burada 1 boyutlu arraylar liste şeklinde gibi düşünülebilir

array([1, 2, 3])

In [66]:
arr2d[2]

array([7, 8, 9])

In [67]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [110, 200, 300]]])

In [70]:
arr3d[0,1,2]

np.int64(6)

In [71]:
arr3d[0][1][2]

np.int64(6)

In [76]:
arr=np.arange(53,61)
arr[4]

np.int64(57)

NUMPY DİZİLERİNİN MAKSİMUM MİNUMUM ELEMANLARIN ERİŞME

In [77]:
arr=np.random.randint(1,100,10)
arr

array([41, 41, 94,  7, 22, 63, 22, 83, 38, 11], dtype=int32)

In [78]:
arr.max()

np.int32(94)

In [79]:
arr.min()

np.int32(7)

In [81]:
arr.argmax()   # maksimum değerinin indeksi

np.int64(2)

NUMPY ARRAYLARİNDE SLİCİNG(DİLİMLEME)

In [82]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
arr[5:10]

array([ 6,  7,  8,  9, 10])

In [84]:
arr[4:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [85]:
arr[2:10:2]

array([3, 5, 7, 9])

In [86]:
arr[5:11]=999  #broadcasting

In [87]:
arr

array([  1,   2,   3,   4,   5, 999, 999, 999, 999, 999, 999,  12])

In [88]:
arr.dtype

dtype('int64')

In [89]:
arr2=np.arange(100,dtype=float)

In [90]:
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [91]:
arr3=np.array(['a','b'])
arr3

array(['a', 'b'], dtype='<U1')

BİR ARRAYİN DTYPE INI DEĞİŞTİRME

In [92]:
arr2.dtype

dtype('float64')

In [93]:
 # .astype( methodu ile )
arr2.astype('int')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])