In [2]:
import numpy as np

matris = np.random.randint(0, 100, (5, 5))

print(matris)


ortalama = np.mean(matris)
standart=np.std(matris)
varyans=np.var(matris)
maksimum=np.max(matris)
minimum=np.min(matris)

i=0
toplam=0
for i in range(5):
   toplam+=matris[i][0]+matris[i][4] 
   i+=1


print("Ortalama:", ortalama)
print("standart sapmasi",standart)
print("varyansi",varyans)
print("en buyuk deger",maksimum)
print("en kucuk deger",minimum)
print("kosegenlerin toplami",toplam)



ortalama = 50      
sapma = 15    
ogrenci= 1000


puanlar = np.random.normal(ortalama, sapma, ogrenci)

puanlar = np.clip(puanlar, 0, 100)

ortalama = np.mean(puanlar)
medyan = np.median(puanlar)
standartsapma = np.std(puanlar)

dusuk = np.sum(puanlar < 50)

print("Ortalama:", ortalama)
print("Medyan:", medyan)
print("Standart Sapma:", standartsapma)
print("50’den dusuk alan ogrenci sayisi:", dusuk)


[[ 7 28 48 83 96]
 [ 4 48 96 80 15]
 [61 50 35 35 10]
 [ 5 24 61 58 61]
 [74 58 12 44 91]]
Ortalama: 47.36
standart sapmasi 28.780382207330046
varyansi 828.3104
en buyuk deger 96
en kucuk deger 4
kosegenlerin toplami 424
Ortalama: 49.96656280114038
Medyan: 50.219692464898344
Standart Sapma: 15.136948076560081
50’den dusuk alan ogrenci sayisi: 493
